services:
  - type: web
    name: afritrad-backend
    env: docker
    dockerContext: .
    dockerFilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: afritrad-db
          property: connectionString
      - key: DB_URL
        fromDatabase:
          name: afritrad-db
          property: connectionString
      - key: APP_KEY
        value: base64:uXKB0w8Ce1VPMDOPqIv/j/864HJNxTy/JB2Tkm29Cio=
      - key: APP_URL
        value: https://afritrade.onrender.com
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: pgsql
      - key: LOG_CHANNEL
        value: errorlog

databases:
  - name: afritrad-db
    databaseName: afritrad
    user: afritrad_user
